### ISSUE TITLE
mix deps.get fails with ex_aws_sns

### ISSUE THREAD

**Issue by chiangf** [ex-aws/ex_aws_sns#1]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6
* ExAws version `mix deps |grep ex_aws`: locked at 2.0.1 (ex_aws) cb2c03c0
* HTTP client version. IE for hackney do `mix deps | grep hackney`: hackney 1.10.1 (Hex package) (rebar3)

### Current behavior

I added the following to mix.exs:
```
defp deps do
    [
        {:ex_aws, "~> 2.0"},
        {:ex_aws_sns, "~> 2.0"}
    ]
end
```

Running `mix deps.get` results in:
```
Failed to fetch record for 'hexpm/ex_aws_sns' from registry (using cache)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix) No package with name ex_aws_sns (from: mix.exs) in registry
```

Does this repo need to be published to hex.pm?

**Comment by edulc** [comment]
I have this same issue. We get a `404` error on https://hex.pm/packages/ex_aws_sns

**Comment by benwilson512** [comment]
Apologies, it doesn't look like this particular version actually got released! I'll fix that promptly.

**Comment by benwilson512** [comment]
It's been released.

**Comment by edulc** [comment]
Thank you @benwilson512! 💯
