### ISSUE TITLE
ExAws.SNS.verify_message has incorrect return type in typespec

### ISSUE THREAD

**Issue by aisrael** [ex-aws/ex_aws_sns#11]
### Environment

* Elixir 1.9.1
* `ex_aws 2.1.1`
* `ex_aws_sns 2.0.1`
* `hackney 1.15.2`

### Current behavior

In [sns.ex:337](https://github.com/ex-aws/ex_aws_sns/blob/master/lib/ex_aws/sns.ex#L337) the `ExAws.SNS.verify_message/1` function has the following typespec:

```
  @spec verify_message(message_params :: %{String.t => String.t}) :: [:ok | {:error, String.t}]
```

### Expected behavior

I think the proper return type in typespec should _not_ have the square brackets:

```
  @spec verify_message(message_params :: %{String.t => String.t}) :: :ok | {:error, String.t}
```

Which is consistent with the actual return values from [`verify/3`](https://github.com/ex-aws/ex_aws_sns/blob/master/lib/ex_aws/sns.ex#L391)

**Comment by warrenseine** [comment]
I think this issue can be closed.
