### ISSUE TITLE
confirm_subscription: Invalid parameter: TopicArn

### ISSUE THREAD

**Issue by keokilee** [ex-aws/ex_aws_sns#3]
### Environment

* Elixir 1.5.2
* ex_aws 2.0.2, ex_aws_sns 2.0.0
* hackney 1.8.6

### Current behavior

Trying to use ExAws.SNS.confirm_subscription to confirm an incoming subscription request.

```
%{"TopicArn" => topic_arn, "Token" => token} = body
response = ExAws.SNS.confirm_subscription(topic_arn, token, false)
|> ExAws.request
```

However, I get the following response:

```
{:error,
 {:http_error, 400,
  %{code: "InvalidParameter", detail: "",
    message: "Invalid parameter: TopicArn",
    request_id: "cc46f3e1-9893-54d6-8bb3-a14fb1b218ca", type: "Sender"}}}
```

Currently, I'm just using `HTTPoison` to follow the `SubscribeURL`.

### Expected behavior

Response should be `:ok` and the subscription should be created.

**Comment by riston** [comment]
Hello @keokilee, I found similar mysterious error debugged half hour the request outputs which all were correctly put together. I found out the default region is set to `us-west-1`, if you use some other region you will hit the same error with other API calls as well. Is there some possibility to handle this error better?

**Comment by sergey-chechaev** [comment]
Just set in config file region for SNS:

```
config :ex_aws,
  access_key_id: ["key_id", :instance_role],
  secret_access_key: ["access_key", :instance_role],
  region: "eu-west-1",
  s3: [
    region: "eu-central-1"
  ],
  sns: [
    region: "eu-central-1"
  ]

```
