### ISSUE TITLE
the "String.Array" is not supported

### ISSUE THREAD

**Issue by HoneyryderChuck** [ex-aws/ex_aws_sns#49]
### Current behavior

Currently, the sns supported attributes are [these](https://github.com/ex-aws/ex_aws_sns/blob/main/lib/ex_aws/sns.ex#L78-L80). Unfortunately, this does not include "String.Array".

### Expected behavior

For the mentioned data type to be supported.

**Comment by bernardd** [comment]
More than happy to have a PR to address this.

**Comment by dcaixinha** [comment]
Hey @bernardd, thanks for merging this :tada: do you plan to make a release soon including this change? :pray:

**Comment by bernardd** [comment]
Yep - I've got a couple more PRs to go over this weekend and hopefully I'll get a release out then.
