### ISSUE TITLE
Breaking change on 2.3.1

### ISSUE THREAD

**Issue by michelboaventura** [ex-aws/ex_aws_sns#59]
Hey,

version 3.2.1 added a compile time requirement for `:ex_aws, :json_codec` configuration that breaks all installations that doesn't have it in place: https://github.com/ex-aws/ex_aws_sns/blob/main/lib/ex_aws/sns.ex#L135.

This configuration is optional on `ex_aws` and falls back to `Jason`, so we can't assume it's there.

Moreover using `Application.fetch_env!/2` on a module body is discouraged and yields a warning on recent elixir.

So I think we could just change this to be handled within `put_value/3` using something like
```elixir
json_codec = Application.get_env(:ex_aws, :json_codec, Jason)
```

or query `ex_aws` directly for the current value.

**Comment by bernardd** [comment]
Ah, thanks - that was my fault, by way of a suggestion I made on that PR. I've changed it as you suggest.
